name: Compile Spark

on:
  workflow_dispatch:

jobs:
  windows:
    name: run on windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: ilammy/msvc-dev-cmd@master
    - name: Build something requiring CL.EXE
        run: |
          cmake -G "NMake Makefiles" .
          nmake

    - name: show files
        run: |
          dir
          tree /f

    # - name: run
    #   run: |
    #     spark.exe test.spark
    #   shell: cmd
    # - name: upload executable
    #   uses: actions/upload-artifact@master
    #   with:
    #     name: windows
    #     path: |
    #       spark.exe
  # mac-and-ubuntu:
  #   runs-on: ${{matrix.os}}
  #   strategy:
  #     matrix:
  #       os: [macos-latest, ubuntu-latest]
  #   name: ${{matrix.os}}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: compile
  #       run: |
  #         g++ -std=c++17 main.cpp -o spark
  #     - name: run
  #       run: |
  #         ./spark test.spark
  #       shell: bash
  #     - name: upload executable
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: ${{matrix.os}}
  #         path: |
  #           spark
          