name: Compile and Upload masscan

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Run on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      
      - name: Compile Visual Studio project with MSBuild
        shell: cmd 
        run: |
              "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && msbuild masscan.vcxproj /p:PlatformToolset=v142 /p:Configuration=Release /p:RuntimeLibrary=MultiThreaded
        working-directory: vs10

      - name: Show Files
        run: |
          dir
          tree /f

      - name: test masscan
        run: |
          .\bin\masscan.exe 
          .\bin\masscan.exe --regress
          .\bin\masscan.exe --iflist

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: masscan
          path: bin/masscan.exe
         